default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kirillzonov
  password:

development:
  <<: *default
  database: test-task-angular_development

test:
  <<: *default
  database: test-task-angular_test

production:
  <<: *default
  database: test-task-angular_production
  username: test-task-angular
  password: <%= ENV['TEST-TASK-ANGULAR_DATABASE_PASSWORD'] %>
